### ISSUE TITLE
Add support for Git Worktrees

### ISSUE THREAD

**Issue by wujek-srujek** [n0mer/gradle-git-properties#14]
Git worktrees allow to checkout multiple working copies at the same time, more here: https://git-scm.com/docs/git-worktree. This plugin doesn't work when the build is triggered within a worktree, it fails with the following error (including just the root cause):

```
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /Users/wujek/Development/IdeaProjects/sample-project/worktrees/develop
at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:581)
at org.eclipse.jgit.api.Git.open(Git.java:116)
at org.eclipse.jgit.api.Git.open(Git.java:99)
at org.eclipse.jgit.api.Git$open.call(Unknown Source)
at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy:84)
at org.ajoberstar.grgit.operation.OpenOp.call(OpenOp.groovy)
at java_util_concurrent_Callable$call$2.call(Unknown Source)
at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
at org.ajoberstar.grgit.Grgit$__clinit__closure1.doCall(Grgit.groovy:193)
at com.gorylenko.GitPropertiesPlugin$GenerateGitPropertiesTask.generate(GitPropertiesPlugin.groovy:50)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
... 75 more
```

More info: the project (its initial clone) is located at /Users/wujek/Development/IdeaProjects/sample-project, and I then created a worktree using 'git worktree add worktrees/develop develop'.

jgit seems to support it already, at least the latest versions: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475.

**Comment by n0mer** [comment]
@wujek-srujek 
mr. srujek, status of https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475 is 'new'.

Please get back when support for git worktrees will appear in stable jGit version

**Comment by smougenot** [comment]
Looks like it is on the way
https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475#c59

> @wujek-srujek
> mr. srujek, status of https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475 is 'new'.
> 
> Please get back when support for git worktrees will appear in stable jGit version

**Comment by mjustin** [comment]
Just to verify: we wouldn't want to manually support this in the plugin until JGit finally gets around to implementing this, correct?

```groovy
// Example; probably not release ready
GitPropertiesPluginExtension(Project project) {
    gitPropertiesDir = project.objects.directoryProperty()
    gitPropertiesResourceDir = project.objects.directoryProperty()
    if (Files.isRegularFile(project.layout.projectDirectory.asFile.toPath().resolve(".git"))) {
        Files.lines(project.layout.projectDirectory.asFile.toPath().resolve(".git")).withCloseable { ditGitFileLines ->
            dotGitDirectory = ditGitFileLines
                    .filter { it.startsWith("gitdir: ") }
                    .map { it.substring('gitdir: '.length(), it.lastIndexOf('/.git/')) }
                    .map { project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(it)) }
                    .findFirst()
                    .orElse(project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(".git")))
        }
    } else {
        dotGitDirectory = project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(".git"))
    }
}
```

**Comment by aspyatkin** [comment]
Kotlin DSL version:

```
gitProperties {
    val dotGitPath = rootProject.layout.projectDirectory.asFile.toPath().resolve(".git")
    if (Files.isRegularFile(dotGitPath)) {
        Files.lines(dotGitPath).use { ditGitFileLines ->
            dotGitDirectory.set(ditGitFileLines
                .filter { it.startsWith("gitdir: ") }
                .map { it.substring("gitdir: ".length, it.lastIndexOf("/.git/")) }
                .map { project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(it)) }
                .findFirst()
                .orElse(project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(".git")))
            )
        }
    }
}
```

**Comment by mjustin** [comment]
I'm currently using a Gradle [initialization script](https://docs.gradle.org/current/userguide/init_scripts.html) to automatically apply [my workaround](https://github.com/n0mer/gradle-git-properties/issues/14#issuecomment-1035608025) to my local projects.  That way it works automatically as needed, and I don't need to pollute the committed build script with workarounds that aren't normally relevant to the other developers on the team.

`$USER_HOME/.gradle/init.d/git-worktree-fix.gradle`:

```groovy
import java.nio.file.Files
import java.nio.file.Path

allprojects {
    plugins.withId('com.gorylenko.gradle-git-properties') {
        gitProperties {
            Path dotGitPath = rootProject.layout.projectDirectory.asFile.toPath().resolve(".git")
            if (Files.isRegularFile(dotGitPath)) {
                Files.lines(dotGitPath).withCloseable { ditGitFileLines ->
                    dotGitDirectory = ditGitFileLines
                            .filter { it.startsWith("gitdir: ") }
                            .map { it.substring('gitdir: '.length(), it.lastIndexOf('/.git/')) }
                            .map { project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(it)) }
                            .findFirst()
                            .orElse(project.objects.directoryProperty().convention(project.layout.projectDirectory.dir(".git")))
                }
            }
        }
    }
}

```

**Comment by yewton** [comment]
My workaround for composite build:

```kts
fun findGitRoot(dir: File?): File {
    if (dir == null) {
        return project.rootDir.resolve(".git")
    }
    val dotGitFile = dir.resolve(".git")
    if (dotGitFile.isFile) {
        return dotGitFile.useLines { ditGitFileLines ->
            ditGitFileLines
                .filter { it.startsWith("gitdir: ") }
                .map { File(it.substring("gitdir: ".length, it.lastIndexOf("/worktrees/"))) }
                .first()
        }
    } else if (dotGitFile.isDirectory) {
        return dotGitFile
    }
    return findGitRoot(dir.parentFile)
}

gitProperties {
    dotGitDirectory = layout.dir(provider { findGitRoot(project.rootDir) })
}
```

**Comment by tompson** [comment]
no workaround needed anymore with version 2.5.3
