### ISSUE TITLE
No such property: out for class: NormalizeEOLOutputStream in JDK 17 EA build.

### ISSUE THREAD

**Issue by sureshg** [n0mer/gradle-git-properties#159]
Using the latest plugin (`id("com.gorylenko.gradle-git-properties") version "2.2.4"`) on JDK 17 throws the `No such property: out` error.

```
------------------------------------------------------------
Gradle 6.8
------------------------------------------------------------

Build time:   2021-01-08 16:38:46 UTC
Revision:     b7e82460c5373e194fb478a998c4fcfe7da53a7e

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17-loom (Oracle Corporation 17-loom+2-42)
OS:           Mac OS X 10.15.7 x86_64
```

```
       at java.base/java.lang.Thread.run(Thread.java:1747)
Caused by: groovy.lang.MissingPropertyException: No such property: out for class: com.gorylenko.writer.NormalizeEOLOutputStream
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
        at com.gorylenko.writer.NormalizeEOLOutputStream.writeEOLs(NormalizeEOLOutputStream.groovy:42)
        at com.gorylenko.writer.NormalizeEOLOutputStream.write(NormalizeEOLOutputStream.groovy:33)
        at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:318)
```

**Comment by sureshg** [comment]
Sorry, nm. It got fixed with `--illegal-access=permit` jvm args
