### ISSUE TITLE
StackOverflowError in Gradle 6.3

### ISSUE THREAD

**Issue by akibabu** [n0mer/gradle-git-properties#193]
This is when executing the task `generateGitProperties` in a typical single module Java project.

When changing to Gradle 6.8.3 it works fine, but Gradle 6.3 gives this error:

```
Caused by: java.lang.StackOverflowError

	at com.gorylenko.GitPropertiesPluginExtension.toString(GitPropertiesPlugin.groovy)

	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.getDisplayName(ManagedObjectFactory.java:141)

	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.toString(ManagedObjectFactory.java:130)

	at org.gradle.api.internal.provider.AbstractProperty.toString(AbstractProperty.java:118)

	at com.gorylenko.GitPropertiesPluginExtension.toString(GitPropertiesPlugin.groovy)

	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.getDisplayName(ManagedObjectFactory.java:141)

	at org.gradle.internal.instantiation.generator.ManagedObjectFactory$ManagedPropertyName.toString(ManagedObjectFactory.java:130)

	at org.gradle.api.internal.provider.AbstractProperty.toString(AbstractProperty.java:118)

	at com.gorylenko.GitPropertiesPluginExtension.toString(GitPropertiesPlugin.groovy)
```

The code in question, that has been modified in the 2.3.1 release

https://github.com/n0mer/gradle-git-properties/blob/45f84f2c9f39cdd908917856e319588da7c4e3fb/src/main/groovy/com/gorylenko/GitPropertiesPlugin.groovy#L57

**Comment by tha2015** [comment]
Because this issue has been resolved since Gradle 6.4 (05/05/2020), I prefer to close this issue instead of updating the plugin, any ideas?

**Comment by tha2015** [comment]
Closing as won't fix - this is a Gradle 6.3 bug that was fixed in Gradle 6.4.

Gradle 6.3 is excluded from the plugin's test matrix (see BackwardCompatibilityFunctionalTest.groovy).

Users experiencing this issue should upgrade to Gradle 6.4+.
